baseURL = 'https://konradwylde.github.io/'
languageCode = "en-us"
theme = "hello-friend-ng"
paginate     = 10
canonifyurls = true
hideHUGOSupport = false

[author]
  name = "0xKNRD"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "SEO Consultant, Cybersecurity enthusiast, Trail runner"
  enableThemeToggle = true
  disableReadOtherPosts = false
  enableSharingButtons = true

  # Metadata
  description = "My new homepage or blog"
  keywords = ""
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[params.footer]
    trademark = true
    rss = false
    copyright = true
    author = false
    topText = ['0xKNRD']
    bottomText = ['']

[languages]
  [languages.en]
    title = "Konrad Zarebski"
    subtitle = "SEO Consultant, Cybersecurity enthusiast, Trail runner"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd home"
      logoHomeLink = "/"
      logoMark= "> $"
      logoCursorColor = "#00FF00"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"


  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/konradzarebski/"

  [[params.social]]
    name = "github"
    url = "https://github.com/konradwylde"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/wildpeakstrailrunning/"

  [[menu.main]]
    identifier = "malware-analysis"
    name       = "Malware Analysis"
    url        = "/malware-analysis"
    weight     = 98

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = 99

[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"